package scanorch

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"
)

// ScanSchedule is a saved Job template that fires
// automatically on an interval. Used for "scan my fleet every
// 6 hours" continuous-monitoring workflows.
//
// Interval-based rather than cron-style: continuous scanning
// for security purposes wants "every N seconds" cadence more
// than wall-clock anchors. A future cycle can add a CronExpr
// alternative — the Scheduler just needs to know when each
// schedule's next tick should fire.
type ScanSchedule struct {
	// ID is the canonical 16-char hex schedule identifier.
	// Generated by Create.
	ID string `json:"id"`
	// Name is an operator-supplied label for the dashboard.
	// Free-form; not unique.
	Name string `json:"name"`
	// Template is the SubmitRequest body fired each interval.
	Template SubmitRequest `json:"template"`
	// IntervalSeconds is the minimum delay between two
	// firings of this schedule. Clamped to [60s, 7d]. Set to
	// 0 (zero value) when CronExpr is in use.
	IntervalSeconds int `json:"interval_seconds,omitempty"`
	// CronExpr (v1.73+) is a 5-field cron expression
	// alternative to IntervalSeconds. Empty when interval-
	// based. Mutually exclusive with IntervalSeconds —
	// exactly one of the two is non-empty per schedule.
	CronExpr string `json:"cron_expr,omitempty"`
	// Timezone (v1.75+) is an IANA zone name (e.g.
	// "America/New_York", "Europe/Madrid") that the
	// Scheduler uses when evaluating CronExpr. Empty = UTC
	// (back-compat with v1.73/v1.74 cron schedules). Only
	// meaningful when CronExpr is set; ignored for interval
	// schedules.
	Timezone string `json:"timezone,omitempty"`
	// Enabled is a soft kill-switch. False schedules stay in
	// the store but the Scheduler skips them. Operators
	// disable instead of delete to preserve history.
	Enabled bool `json:"enabled"`
	// Operator is the identity that created the schedule.
	Operator string `json:"operator,omitempty"`
	// CreatedAt is when Create was called.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt (v1.78+) is the timestamp of the most-
	// recent state change to the schedule's editable
	// fields. Set on Create (= CreatedAt) and bumped on
	// every Update. Used by the optimistic-locking
	// If-Match precondition — operators editing a
	// schedule that another operator has already changed
	// see a 412 instead of overwriting blind. Not bumped
	// by MarkFired or SetEnabled (those don't touch the
	// editable fields).
	UpdatedAt time.Time `json:"updated_at"`
	// LastFiredAt is the timestamp of the most-recent
	// auto-fire. Zero until the first fire. The Scheduler
	// uses (LastFiredAt + IntervalSeconds) to decide
	// "is this due now?".
	LastFiredAt time.Time `json:"last_fired_at,omitempty"`
	// NextFireAt (v1.77+) is the predicted next firing time
	// for this schedule, computed at read time and NOT
	// persisted. Zero value when the schedule won't fire
	// (disabled, invalid cron, or a cron expression with no
	// match within the look-ahead window). Set by the REST
	// layer after fetching from the store; the in-memory and
	// DB stores both leave it at zero. The store does not
	// touch this field on writes — serialisation by the
	// handler is the only consumer.
	NextFireAt time.Time `json:"next_fire_at,omitempty"`
}

// CreateScheduleRequest is the dashboard's request body. The
// store generates ID + CreatedAt; everything else comes from
// the operator.
//
// **Cadence (v1.73+)**: exactly one of IntervalSeconds or
// CronExpr must be non-zero/non-empty. Both set → error;
// neither set → ErrScheduleCadenceRequired. CronExpr passes
// through ParseCron at Create time so a bad expression
// fails fast instead of at the next tick.
type CreateScheduleRequest struct {
	Name            string        `json:"name"`
	Template        SubmitRequest `json:"template"`
	IntervalSeconds int           `json:"interval_seconds,omitempty"`
	CronExpr        string        `json:"cron_expr,omitempty"`
	// Timezone (v1.75+, optional) IANA name for cron
	// evaluation. Ignored for interval schedules.
	Timezone string `json:"timezone,omitempty"`
}

// IntervalSeconds clamping bounds. Lower bound prevents an
// operator from accidentally creating a 1-Hz scanner that
// hammers the worker pool. Upper bound is "weekly" — if you
// want monthly, run a manual scan.
const (
	scheduleMinInterval = 60               // 1 minute
	scheduleMaxInterval = 7 * 24 * 60 * 60 // 7 days
)

// Sentinel errors.
var (
	// ErrScheduleNameRequired means CreateScheduleRequest's
	// Name was empty.
	ErrScheduleNameRequired = errors.New("scanorch: schedule name is required")
	// ErrScheduleTemplateInputRequired means the template's
	// Input was empty.
	ErrScheduleTemplateInputRequired = errors.New("scanorch: schedule template input is required")
	// ErrScheduleNotFound is returned by Get / Delete when no
	// schedule has the requested ID.
	ErrScheduleNotFound = errors.New("scanorch: schedule not found")
	// ErrScheduleCadenceRequired (v1.73+) means
	// CreateScheduleRequest had neither IntervalSeconds nor
	// CronExpr set.
	ErrScheduleCadenceRequired = errors.New("scanorch: schedule must specify either interval_seconds or cron_expr")
	// ErrScheduleCadenceConflict (v1.73+) means
	// CreateScheduleRequest set both IntervalSeconds AND
	// CronExpr — ambiguous.
	ErrScheduleCadenceConflict = errors.New("scanorch: schedule cannot specify both interval_seconds and cron_expr")
	// ErrScheduleInvalidTimezone (v1.75+) means the supplied
	// IANA timezone name failed time.LoadLocation lookup. The
	// underlying error wraps to give the operator the actual
	// reason (typo, missing tzdata, etc).
	ErrScheduleInvalidTimezone = errors.New("scanorch: schedule timezone invalid")
	// ErrSchedulePreconditionFailed (v1.78+) means an Update
	// supplied an IfMatch precondition that didn't match the
	// stored UpdatedAt. Surfaces as 412 in REST. Operators
	// see a clear "the schedule was modified by another
	// operator — refresh and retry" message instead of a
	// silent overwrite.
	ErrSchedulePreconditionFailed = errors.New("scanorch: schedule precondition failed")
)

// ScheduleStore is the persistence interface for scan
// schedules. The v1.70 in-memory implementation lives below;
// future cycles may add a DB-backed Store mirroring DBStore.
type ScheduleStore interface {
	Create(ctx context.Context, req CreateScheduleRequest, operator string) (ScanSchedule, error)
	Get(ctx context.Context, id string) (ScanSchedule, error)
	List(ctx context.Context) ([]ScanSchedule, error)
	Delete(ctx context.Context, id string) error
	// Update (v1.74+) replaces the editable fields of an
	// existing schedule. ID, CreatedAt, LastFiredAt, and
	// Operator are immutable. Validation mirrors Create's
	// rules: name + template.input non-empty; exactly one
	// cadence; cron parses if specified.
	//
	// v1.78+: req.IfMatch (when non-nil) is the optimistic
	// locking precondition. If it doesn't match the stored
	// UpdatedAt, returns ErrSchedulePreconditionFailed
	// (mapped to 412 in REST). Nil IfMatch skips the check
	// — back-compat for v1.74-v1.77 callers.
	Update(ctx context.Context, id string, req UpdateScheduleRequest) (ScanSchedule, error)
	// MarkFired stamps LastFiredAt to now and persists. The
	// Scheduler calls this after a successful Submit so the
	// next tick computes the right "due" check.
	MarkFired(ctx context.Context, id string, now time.Time) error
	// SetEnabled toggles the kill-switch. Disabled schedules
	// stay in the store but the Scheduler skips them.
	SetEnabled(ctx context.Context, id string, enabled bool) error
}

// UpdateScheduleRequest is the dashboard's edit body. Same
// shape as CreateScheduleRequest minus the operator (immutable
// — preserves audit trail of who created the schedule).
//
// Validation: same rules as Create — name + template.input
// non-empty; exactly one cadence; cron parses if specified.
type UpdateScheduleRequest struct {
	Name            string        `json:"name"`
	Template        SubmitRequest `json:"template"`
	IntervalSeconds int           `json:"interval_seconds,omitempty"`
	CronExpr        string        `json:"cron_expr,omitempty"`
	// Timezone (v1.75+, optional) IANA name for cron
	// evaluation. Empty resets to UTC.
	Timezone string `json:"timezone,omitempty"`
	// IfMatch (v1.78+) is the optimistic-locking
	// precondition. When non-nil, the Update only
	// proceeds if the schedule's stored UpdatedAt equals
	// IfMatch. Mismatch yields ErrSchedulePreconditionFailed
	// (mapped to 412 in REST). Nil IfMatch skips the check
	// — back-compat with v1.74-v1.77 callers.
	//
	// Set by the REST handler from the `If-Match` HTTP
	// header (RFC3339 timestamp). Direct Go callers can
	// populate it directly. JSON-skipped because it
	// belongs in the header, not the body.
	IfMatch *time.Time `json:"-"`
}

// MemoryScheduleStore is the in-memory ScheduleStore. v1.70+.
// Goroutine-safe via a single RWMutex around the map.
type MemoryScheduleStore struct {
	mu        sync.RWMutex
	schedules map[string]ScanSchedule
}

// NewMemoryScheduleStore returns a fresh store.
func NewMemoryScheduleStore() *MemoryScheduleStore {
	return &MemoryScheduleStore{schedules: make(map[string]ScanSchedule)}
}

// Create validates + clamps + stores.
func (s *MemoryScheduleStore) Create(_ context.Context, req CreateScheduleRequest, operator string) (ScanSchedule, error) {
	sched, err := buildScheduleFromRequest(req, operator)
	if err != nil {
		return ScanSchedule{}, err
	}
	s.mu.Lock()
	s.schedules[sched.ID] = sched
	s.mu.Unlock()
	return sched, nil
}

// buildScheduleFromRequest validates the request + applies
// clamping + parses the cron expression. Returned ScanSchedule
// is ready to persist (ID generated, CreatedAt stamped). Used
// by both MemoryScheduleStore and DBScheduleStore so the
// validation rules are a single source of truth.
//
// Validation order (matters for the operator's error message):
//
//  1. Name non-empty.
//  2. Template input non-empty.
//  3. Cadence specified (exactly one of interval / cron).
//  4. Cron expression parses (defer cron parse until cadence
//     is settled to avoid noisy errors).
func buildScheduleFromRequest(req CreateScheduleRequest, operator string) (ScanSchedule, error) {
	if err := validateScheduleFields(req.Name, req.Template, req.IntervalSeconds, req.CronExpr, req.Timezone); err != nil {
		return ScanSchedule{}, err
	}
	id, err := generateID()
	if err != nil {
		return ScanSchedule{}, err
	}
	now := time.Now().UTC().Truncate(time.Microsecond)
	sched := ScanSchedule{
		ID:        id,
		Name:      req.Name,
		Template:  req.Template,
		Timezone:  req.Timezone,
		Enabled:   true,
		Operator:  operator,
		CreatedAt: now,
		// v1.78+: UpdatedAt = CreatedAt at creation time.
		// Future Updates bump this; the optimistic-locking
		// If-Match check compares against this value.
		UpdatedAt: now,
	}
	applyCadence(&sched, req.IntervalSeconds, req.CronExpr)
	return sched, nil
}

// validateScheduleFields enforces the shared validation rules
// for both Create and Update — name + template.input
// non-empty; exactly one cadence; cron parses if specified;
// timezone (if non-empty) loads via time.LoadLocation.
//
// Timezone is only validated when CronExpr is set — interval
// schedules ignore the timezone field. Operators who supply
// a timezone with an interval schedule see it stored but
// unused (better than rejecting; lets the operator switch
// modes via Update without re-typing the zone).
func validateScheduleFields(name string, template SubmitRequest, intervalSeconds int, cronExpr, timezone string) error {
	if name == "" {
		return ErrScheduleNameRequired
	}
	if template.Input == "" {
		return ErrScheduleTemplateInputRequired
	}
	hasInterval := intervalSeconds > 0
	hasCron := cronExpr != ""
	switch {
	case hasInterval && hasCron:
		return ErrScheduleCadenceConflict
	case !hasInterval && !hasCron:
		return ErrScheduleCadenceRequired
	}
	if hasCron {
		if _, err := ParseCron(cronExpr); err != nil {
			return err
		}
	}
	if timezone != "" {
		if _, err := time.LoadLocation(timezone); err != nil {
			return fmt.Errorf("%w: %s: %w", ErrScheduleInvalidTimezone, timezone, err)
		}
	}
	return nil
}

// applyCadence sets either IntervalSeconds (clamped) or
// CronExpr on the schedule. Caller must have already validated
// via validateScheduleFields — applyCadence assumes exactly
// one of the two is set.
func applyCadence(s *ScanSchedule, intervalSeconds int, cronExpr string) {
	// Reset both fields so an Update that switches modes
	// doesn't leave the previous-mode field set.
	s.IntervalSeconds = 0
	s.CronExpr = ""
	if intervalSeconds > 0 {
		s.IntervalSeconds = clampInterval(intervalSeconds)
	} else {
		s.CronExpr = cronExpr
	}
}

// clampInterval applies the [60s, 7d] bounds.
func clampInterval(v int) int {
	if v < scheduleMinInterval {
		return scheduleMinInterval
	}
	if v > scheduleMaxInterval {
		return scheduleMaxInterval
	}
	return v
}

// Get returns the schedule by ID.
func (s *MemoryScheduleStore) Get(_ context.Context, id string) (ScanSchedule, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	sched, ok := s.schedules[id]
	if !ok {
		return ScanSchedule{}, ErrScheduleNotFound
	}
	return sched, nil
}

// List returns every schedule. Sorted by Name for stable
// dashboard display.
func (s *MemoryScheduleStore) List(_ context.Context) ([]ScanSchedule, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]ScanSchedule, 0, len(s.schedules))
	for _, sched := range s.schedules {
		out = append(out, sched)
	}
	sortSchedulesByName(out)
	return out, nil
}

// Delete removes the schedule.
func (s *MemoryScheduleStore) Delete(_ context.Context, id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, ok := s.schedules[id]; !ok {
		return ErrScheduleNotFound
	}
	delete(s.schedules, id)
	return nil
}

// Update replaces the editable fields of an existing
// schedule. ID, CreatedAt, LastFiredAt, Operator, Enabled
// are preserved. v1.74+.
//
// v1.78+: enforces optimistic-locking via req.IfMatch. If
// non-nil and the stored UpdatedAt differs, returns
// ErrSchedulePreconditionFailed without modifying the
// schedule. Bumps UpdatedAt on success.
func (s *MemoryScheduleStore) Update(_ context.Context, id string, req UpdateScheduleRequest) (ScanSchedule, error) {
	if err := validateScheduleFields(req.Name, req.Template, req.IntervalSeconds, req.CronExpr, req.Timezone); err != nil {
		return ScanSchedule{}, err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	sched, ok := s.schedules[id]
	if !ok {
		return ScanSchedule{}, ErrScheduleNotFound
	}
	if req.IfMatch != nil && !sched.UpdatedAt.Equal(*req.IfMatch) {
		return ScanSchedule{}, ErrSchedulePreconditionFailed
	}
	sched.Name = req.Name
	sched.Template = req.Template
	sched.Timezone = req.Timezone
	applyCadence(&sched, req.IntervalSeconds, req.CronExpr)
	sched.UpdatedAt = time.Now().UTC().Truncate(time.Microsecond)
	s.schedules[id] = sched
	return sched, nil
}

// MarkFired updates LastFiredAt.
func (s *MemoryScheduleStore) MarkFired(_ context.Context, id string, now time.Time) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	sched, ok := s.schedules[id]
	if !ok {
		return ErrScheduleNotFound
	}
	sched.LastFiredAt = now.UTC().Truncate(time.Microsecond)
	s.schedules[id] = sched
	return nil
}

// SetEnabled toggles the kill-switch.
func (s *MemoryScheduleStore) SetEnabled(_ context.Context, id string, enabled bool) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	sched, ok := s.schedules[id]
	if !ok {
		return ErrScheduleNotFound
	}
	sched.Enabled = enabled
	s.schedules[id] = sched
	return nil
}

// sortSchedulesByName is a tiny in-place sort by Name. Avoids
// importing sort just for this; the schedule count per
// deployment is small (typically <50).
func sortSchedulesByName(s []ScanSchedule) {
	// Insertion sort: O(N^2) worst-case but N is small +
	// already-sorted is O(N).
	for i := 1; i < len(s); i++ {
		v := s[i]
		j := i - 1
		for j >= 0 && s[j].Name > v.Name {
			s[j+1] = s[j]
			j--
		}
		s[j+1] = v
	}
}

// IsDue reports whether the schedule should fire at `now`.
// Returns false if disabled. v1.73+: cron-based schedules
// compute the next-fire-time via CronExpr.Next(LastFiredAt or
// CreatedAt) and check now >= that. Interval-based schedules
// keep the v1.70 behaviour.
//
// Never-fired schedules:
//   - Interval-based: fire on the next tick (eager).
//   - Cron-based: fire when the cron schedule's next-after-
//     CreatedAt has passed. Operators creating "0 2 * * *"
//     at 13:00 don't get an immediate fire — they wait for
//     the next 02:00.
func (s ScanSchedule) IsDue(now time.Time) bool {
	if !s.Enabled {
		return false
	}
	if s.CronExpr != "" {
		return s.cronIsDue(now)
	}
	if s.LastFiredAt.IsZero() {
		return true
	}
	return now.Sub(s.LastFiredAt) >= time.Duration(s.IntervalSeconds)*time.Second
}

// cronIsDue handles the v1.73+ cron path. Compares now against
// CronExpr.Next(anchor) where anchor is LastFiredAt or
// CreatedAt for never-fired schedules.
//
// v1.75+: now and anchor are both converted to s.Timezone
// before the cron match. Empty Timezone falls back to UTC.
//
// v1.77+: factored to share the next-fire computation with
// cronNextFire. A cron parse / timezone error returns false
// (defence in depth — should have been caught at Create
// time).
func (s ScanSchedule) cronIsDue(now time.Time) bool {
	next := s.cronNextFire(now)
	if next.IsZero() {
		return false
	}
	loc := time.UTC
	if s.Timezone != "" {
		if l, err := time.LoadLocation(s.Timezone); err == nil {
			loc = l
		}
	}
	return !now.In(loc).Before(next.In(loc))
}

// NextFire (v1.77+) returns the predicted next fire time for
// this schedule, or the zero time if it cannot be predicted
// (disabled, never-matches-cron, or invalid timezone — all
// these are surface-via-zero rather than as errors so the
// dashboard can render "—" cleanly).
//
// Used by:
//   - the REST read paths (Get/List/Create/Update populate
//     NextFireAt before serialising).
//   - the /api/v1/schedules/preview endpoint (operators see
//     what their cadence will produce before submitting).
//
// For cron schedules NextFire returns the literal next match
// against the anchor (LastFiredAt or CreatedAt); for
// overdue schedules this can be in the past, which the
// dashboard renders as "overdue" so the operator knows the
// next tick will fire it.
//
// For interval schedules NextFire returns:
//   - now (effectively) when the schedule has never fired
//     (eager-fire on the next scheduler tick).
//   - LastFiredAt + IntervalSeconds otherwise.
func (s ScanSchedule) NextFire(now time.Time) time.Time {
	if !s.Enabled {
		return time.Time{}
	}
	if s.CronExpr != "" {
		return s.cronNextFire(now)
	}
	return s.intervalNextFire(now)
}

// intervalNextFire predicts the next fire for interval
// schedules. Never-fired returns now (eager); otherwise
// LastFiredAt + IntervalSeconds. The result is clipped to
// not-before-now would be a usability win for the dashboard,
// but it's also misleading for overdue schedules — better to
// surface the real predicted time + let the UI label it.
func (s ScanSchedule) intervalNextFire(now time.Time) time.Time {
	if s.LastFiredAt.IsZero() {
		return now.UTC().Truncate(time.Second)
	}
	return s.LastFiredAt.Add(time.Duration(s.IntervalSeconds) * time.Second)
}

// cronNextFire is the cron-path predictor shared between
// cronIsDue and NextFire. Returns the next match in UTC; zero
// time on parse / timezone error.
func (s ScanSchedule) cronNextFire(_ time.Time) time.Time {
	c, err := ParseCron(s.CronExpr)
	if err != nil {
		return time.Time{}
	}
	loc := time.UTC
	if s.Timezone != "" {
		l, err := time.LoadLocation(s.Timezone)
		if err != nil {
			return time.Time{}
		}
		loc = l
	}
	anchor := s.LastFiredAt
	if anchor.IsZero() {
		anchor = s.CreatedAt
	}
	next, err := c.Next(anchor.In(loc))
	if err != nil {
		return time.Time{}
	}
	return next.UTC()
}

// PreviewNextFire (v1.77+) validates a CreateScheduleRequest
// and returns the predicted next fire time without
// persisting. Used by the /api/v1/schedules/preview endpoint
// so operators can see what their cadence will produce
// before clicking submit. Validation surface mirrors Create
// (same sentinels for cadence + timezone errors).
func PreviewNextFire(req CreateScheduleRequest, now time.Time) (time.Time, error) {
	if err := validateScheduleFields(req.Name, req.Template, req.IntervalSeconds, req.CronExpr, req.Timezone); err != nil {
		return time.Time{}, err
	}
	// Synthesise a minimal in-memory ScanSchedule so we can
	// reuse the NextFire helpers. Operator + ID + CreatedAt
	// are set to plausible values — CreatedAt = now is the
	// "as-if-just-created" anchor.
	s := ScanSchedule{
		Name:            req.Name,
		Template:        req.Template,
		IntervalSeconds: req.IntervalSeconds,
		CronExpr:        req.CronExpr,
		Timezone:        req.Timezone,
		Enabled:         true,
		CreatedAt:       now.UTC(),
	}
	return s.NextFire(now), nil
}

// Compile-time guard.
var _ ScheduleStore = (*MemoryScheduleStore)(nil)
