package scanorch

import (
	"context"
	"errors"
	"sync"
	"time"
)

// ScanSchedule is a saved Job template that fires
// automatically on an interval. Used for "scan my fleet every
// 6 hours" continuous-monitoring workflows.
//
// Interval-based rather than cron-style: continuous scanning
// for security purposes wants "every N seconds" cadence more
// than wall-clock anchors. A future cycle can add a CronExpr
// alternative — the Scheduler just needs to know when each
// schedule's next tick should fire.
type ScanSchedule struct {
	// ID is the canonical 16-char hex schedule identifier.
	// Generated by Create.
	ID string `json:"id"`
	// Name is an operator-supplied label for the dashboard.
	// Free-form; not unique.
	Name string `json:"name"`
	// Template is the SubmitRequest body fired each interval.
	Template SubmitRequest `json:"template"`
	// IntervalSeconds is the minimum delay between two
	// firings of this schedule. Clamped to [60s, 7d]. Set to
	// 0 (zero value) when CronExpr is in use.
	IntervalSeconds int `json:"interval_seconds,omitempty"`
	// CronExpr (v1.73+) is a 5-field cron expression
	// alternative to IntervalSeconds. Empty when interval-
	// based. Mutually exclusive with IntervalSeconds —
	// exactly one of the two is non-empty per schedule.
	CronExpr string `json:"cron_expr,omitempty"`
	// Enabled is a soft kill-switch. False schedules stay in
	// the store but the Scheduler skips them. Operators
	// disable instead of delete to preserve history.
	Enabled bool `json:"enabled"`
	// Operator is the identity that created the schedule.
	Operator string `json:"operator,omitempty"`
	// CreatedAt is when Create was called.
	CreatedAt time.Time `json:"created_at"`
	// LastFiredAt is the timestamp of the most-recent
	// auto-fire. Zero until the first fire. The Scheduler
	// uses (LastFiredAt + IntervalSeconds) to decide
	// "is this due now?".
	LastFiredAt time.Time `json:"last_fired_at,omitempty"`
}

// CreateScheduleRequest is the dashboard's request body. The
// store generates ID + CreatedAt; everything else comes from
// the operator.
//
// **Cadence (v1.73+)**: exactly one of IntervalSeconds or
// CronExpr must be non-zero/non-empty. Both set → error;
// neither set → ErrScheduleCadenceRequired. CronExpr passes
// through ParseCron at Create time so a bad expression
// fails fast instead of at the next tick.
type CreateScheduleRequest struct {
	Name            string        `json:"name"`
	Template        SubmitRequest `json:"template"`
	IntervalSeconds int           `json:"interval_seconds,omitempty"`
	CronExpr        string        `json:"cron_expr,omitempty"`
}

// IntervalSeconds clamping bounds. Lower bound prevents an
// operator from accidentally creating a 1-Hz scanner that
// hammers the worker pool. Upper bound is "weekly" — if you
// want monthly, run a manual scan.
const (
	scheduleMinInterval = 60               // 1 minute
	scheduleMaxInterval = 7 * 24 * 60 * 60 // 7 days
)

// Sentinel errors.
var (
	// ErrScheduleNameRequired means CreateScheduleRequest's
	// Name was empty.
	ErrScheduleNameRequired = errors.New("scanorch: schedule name is required")
	// ErrScheduleTemplateInputRequired means the template's
	// Input was empty.
	ErrScheduleTemplateInputRequired = errors.New("scanorch: schedule template input is required")
	// ErrScheduleNotFound is returned by Get / Delete when no
	// schedule has the requested ID.
	ErrScheduleNotFound = errors.New("scanorch: schedule not found")
	// ErrScheduleCadenceRequired (v1.73+) means
	// CreateScheduleRequest had neither IntervalSeconds nor
	// CronExpr set.
	ErrScheduleCadenceRequired = errors.New("scanorch: schedule must specify either interval_seconds or cron_expr")
	// ErrScheduleCadenceConflict (v1.73+) means
	// CreateScheduleRequest set both IntervalSeconds AND
	// CronExpr — ambiguous.
	ErrScheduleCadenceConflict = errors.New("scanorch: schedule cannot specify both interval_seconds and cron_expr")
)

// ScheduleStore is the persistence interface for scan
// schedules. The v1.70 in-memory implementation lives below;
// future cycles may add a DB-backed Store mirroring DBStore.
type ScheduleStore interface {
	Create(ctx context.Context, req CreateScheduleRequest, operator string) (ScanSchedule, error)
	Get(ctx context.Context, id string) (ScanSchedule, error)
	List(ctx context.Context) ([]ScanSchedule, error)
	Delete(ctx context.Context, id string) error
	// MarkFired stamps LastFiredAt to now and persists. The
	// Scheduler calls this after a successful Submit so the
	// next tick computes the right "due" check.
	MarkFired(ctx context.Context, id string, now time.Time) error
	// SetEnabled toggles the kill-switch. Disabled schedules
	// stay in the store but the Scheduler skips them.
	SetEnabled(ctx context.Context, id string, enabled bool) error
}

// MemoryScheduleStore is the in-memory ScheduleStore. v1.70+.
// Goroutine-safe via a single RWMutex around the map.
type MemoryScheduleStore struct {
	mu        sync.RWMutex
	schedules map[string]ScanSchedule
}

// NewMemoryScheduleStore returns a fresh store.
func NewMemoryScheduleStore() *MemoryScheduleStore {
	return &MemoryScheduleStore{schedules: make(map[string]ScanSchedule)}
}

// Create validates + clamps + stores.
func (s *MemoryScheduleStore) Create(_ context.Context, req CreateScheduleRequest, operator string) (ScanSchedule, error) {
	sched, err := buildScheduleFromRequest(req, operator)
	if err != nil {
		return ScanSchedule{}, err
	}
	s.mu.Lock()
	s.schedules[sched.ID] = sched
	s.mu.Unlock()
	return sched, nil
}

// buildScheduleFromRequest validates the request + applies
// clamping + parses the cron expression. Returned ScanSchedule
// is ready to persist (ID generated, CreatedAt stamped). Used
// by both MemoryScheduleStore and DBScheduleStore so the
// validation rules are a single source of truth.
//
// Validation order (matters for the operator's error message):
//
//  1. Name non-empty.
//  2. Template input non-empty.
//  3. Cadence specified (exactly one of interval / cron).
//  4. Cron expression parses (defer cron parse until cadence
//     is settled to avoid noisy errors).
func buildScheduleFromRequest(req CreateScheduleRequest, operator string) (ScanSchedule, error) {
	if req.Name == "" {
		return ScanSchedule{}, ErrScheduleNameRequired
	}
	if req.Template.Input == "" {
		return ScanSchedule{}, ErrScheduleTemplateInputRequired
	}
	hasInterval := req.IntervalSeconds > 0
	hasCron := req.CronExpr != ""
	switch {
	case hasInterval && hasCron:
		return ScanSchedule{}, ErrScheduleCadenceConflict
	case !hasInterval && !hasCron:
		return ScanSchedule{}, ErrScheduleCadenceRequired
	}
	if hasCron {
		if _, err := ParseCron(req.CronExpr); err != nil {
			return ScanSchedule{}, err
		}
	}
	id, err := generateID()
	if err != nil {
		return ScanSchedule{}, err
	}
	now := time.Now().UTC().Truncate(time.Microsecond)
	sched := ScanSchedule{
		ID:        id,
		Name:      req.Name,
		Template:  req.Template,
		Enabled:   true,
		Operator:  operator,
		CreatedAt: now,
	}
	if hasInterval {
		sched.IntervalSeconds = clampInterval(req.IntervalSeconds)
	} else {
		sched.CronExpr = req.CronExpr
	}
	return sched, nil
}

// clampInterval applies the [60s, 7d] bounds.
func clampInterval(v int) int {
	if v < scheduleMinInterval {
		return scheduleMinInterval
	}
	if v > scheduleMaxInterval {
		return scheduleMaxInterval
	}
	return v
}

// Get returns the schedule by ID.
func (s *MemoryScheduleStore) Get(_ context.Context, id string) (ScanSchedule, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	sched, ok := s.schedules[id]
	if !ok {
		return ScanSchedule{}, ErrScheduleNotFound
	}
	return sched, nil
}

// List returns every schedule. Sorted by Name for stable
// dashboard display.
func (s *MemoryScheduleStore) List(_ context.Context) ([]ScanSchedule, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]ScanSchedule, 0, len(s.schedules))
	for _, sched := range s.schedules {
		out = append(out, sched)
	}
	sortSchedulesByName(out)
	return out, nil
}

// Delete removes the schedule.
func (s *MemoryScheduleStore) Delete(_ context.Context, id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, ok := s.schedules[id]; !ok {
		return ErrScheduleNotFound
	}
	delete(s.schedules, id)
	return nil
}

// MarkFired updates LastFiredAt.
func (s *MemoryScheduleStore) MarkFired(_ context.Context, id string, now time.Time) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	sched, ok := s.schedules[id]
	if !ok {
		return ErrScheduleNotFound
	}
	sched.LastFiredAt = now.UTC().Truncate(time.Microsecond)
	s.schedules[id] = sched
	return nil
}

// SetEnabled toggles the kill-switch.
func (s *MemoryScheduleStore) SetEnabled(_ context.Context, id string, enabled bool) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	sched, ok := s.schedules[id]
	if !ok {
		return ErrScheduleNotFound
	}
	sched.Enabled = enabled
	s.schedules[id] = sched
	return nil
}

// sortSchedulesByName is a tiny in-place sort by Name. Avoids
// importing sort just for this; the schedule count per
// deployment is small (typically <50).
func sortSchedulesByName(s []ScanSchedule) {
	// Insertion sort: O(N^2) worst-case but N is small +
	// already-sorted is O(N).
	for i := 1; i < len(s); i++ {
		v := s[i]
		j := i - 1
		for j >= 0 && s[j].Name > v.Name {
			s[j+1] = s[j]
			j--
		}
		s[j+1] = v
	}
}

// IsDue reports whether the schedule should fire at `now`.
// Returns false if disabled. v1.73+: cron-based schedules
// compute the next-fire-time via CronExpr.Next(LastFiredAt or
// CreatedAt) and check now >= that. Interval-based schedules
// keep the v1.70 behaviour.
//
// Never-fired schedules:
//   - Interval-based: fire on the next tick (eager).
//   - Cron-based: fire when the cron schedule's next-after-
//     CreatedAt has passed. Operators creating "0 2 * * *"
//     at 13:00 don't get an immediate fire — they wait for
//     the next 02:00.
func (s ScanSchedule) IsDue(now time.Time) bool {
	if !s.Enabled {
		return false
	}
	if s.CronExpr != "" {
		return s.cronIsDue(now)
	}
	if s.LastFiredAt.IsZero() {
		return true
	}
	return now.Sub(s.LastFiredAt) >= time.Duration(s.IntervalSeconds)*time.Second
}

// cronIsDue handles the v1.73+ cron path. Compares now against
// CronExpr.Next(anchor) where anchor is LastFiredAt or
// CreatedAt for never-fired schedules. A cron parse error
// here is fatal — should have been caught at Create time, so
// this is defence in depth (returns false to skip the
// schedule rather than panic).
func (s ScanSchedule) cronIsDue(now time.Time) bool {
	c, err := ParseCron(s.CronExpr)
	if err != nil {
		return false
	}
	anchor := s.LastFiredAt
	if anchor.IsZero() {
		anchor = s.CreatedAt
	}
	next, err := c.Next(anchor)
	if err != nil {
		return false
	}
	return !now.Before(next)
}

// Compile-time guard.
var _ ScheduleStore = (*MemoryScheduleStore)(nil)
